In [3]:
import numpy as np

In [4]:
oneD = np.array([1,2,3,4,5,6,7,8,9])

In [5]:
oneD

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(oneD)

numpy.ndarray

In [7]:
oneD.ndim # tells us the dimension of an array

1

In [9]:
zeroD = np.array(100) #without brackets its not vector scalar

In [11]:
zeroD.ndim # the dimesnion of scalar are always 0

0

In [12]:
twoD = np.array([[100]])

In [13]:
twoD.ndim

2

In [14]:
zeroD.shape #tels us the number of rows and columns

()

In [15]:
twoD.shape

(1, 1)

In [16]:
oneD.shape

(9,)

In [22]:
twoD2 =  np.array([[1,2,3,4],[1,2,3,5],[1,2,3,6]]) #the inner brackets are of rows

In [23]:
twoD2.shape

(3, 4)

#scalar = 0D tensor
#vector = 1d tensor
#tenso = nD tensor

In [24]:
oneD = np.arange(10)

In [25]:
oneD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
twoD = np.arange(10).reshape(2,5) # can only be reshaped into factors of 10

In [29]:
twoD

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]) # np. of brackets at beginning shows number of dimensions

In [33]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [35]:
threeD.shape #(2,3,3) 2 here represents depth

(2, 3, 3)

In [36]:
threeD = np.arange(100).reshape(4,5,5)

In [37]:
threeD

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [40]:
threeD = np.array([[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]],[[1,2],[3,4],[5,6],[7,8]]])

In [42]:
threeD

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [43]:
threeD.shape

(3, 4, 2)

# Data Type

In [44]:
a = np.array([1,2,3,4])

In [45]:
a.dtype

dtype('int32')

In [46]:
b = np.array([1,2.5,3,4])

In [47]:
b.dtype

dtype('float64')

In [48]:
b = np.array([1,2.5,3,4], dtype = "int32")

In [49]:
b.dtype

dtype('int32')

In [50]:
b

array([1, 2, 3, 4])

In [51]:
a = a.astype("float64")

In [52]:
a

array([1., 2., 3., 4.])

In [53]:
a.dtype

dtype('float64')

In [54]:
aList = [1,2,3,4,5,6,7,8,9]

In [56]:
# multiplying each element of Alist with 5
bList = []
for num in aList:
    bList.append(num*5)
print(bList)

[5, 10, 15, 20, 25, 30, 35, 40, 45]


In [61]:
aList = np.arange(10)*5

In [62]:
aList

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [63]:
aList + aList

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
t1 = np.random.rand(2,3)*10

In [65]:
t1

array([[3.95042926, 8.91504235, 5.79018802],
       [9.22729708, 7.92614038, 3.87151387]])

In [66]:
t2 = np.random.rand(2,3)*10
t2

array([[2.74720046, 1.43058059, 2.58169982],
       [0.39301971, 8.84952974, 9.39031059]])

In [71]:
t1.shape == t2.shape

True

In [67]:
t1 + t2

array([[ 6.69762972, 10.34562294,  8.37188784],
       [ 9.62031679, 16.77567012, 13.26182447]])

In [68]:
t1 - t2

array([[ 1.2032288 ,  7.48446175,  3.2084882 ],
       [ 8.83427737, -0.92338936, -5.51879672]])

In [72]:
t1 * t2 # element to element multiplication

array([[10.85262107, 12.75368655, 14.94852737],
       [ 3.62650962, 70.14261502, 36.35471774]])

In [73]:
t1/t2

array([[ 1.43798362,  6.2317652 ,  2.24278127],
       [23.47794998,  0.89565667,  0.41228816]])

In [74]:
t1.shape

(2, 3)

In [75]:
t2.shape

(2, 3)

In [76]:
t3 = np.arange(9).reshape(3,3)

In [77]:
t1.shape , t3.shape

((2, 3), (3, 3))

In [78]:
t1@t3 # linear algebra rule multiplication

array([[61.48625514, 80.14191476, 98.79757438],
       [47.00750439, 68.03245572, 89.05740706]])

In [79]:
np.dot(t1,t3) # linear algebra rule multiplication

array([[61.48625514, 80.14191476, 98.79757438],
       [47.00750439, 68.03245572, 89.05740706]])

In [80]:
t1.dot(t3) # linear algebra rule multiplication

array([[61.48625514, 80.14191476, 98.79757438],
       [47.00750439, 68.03245572, 89.05740706]])

In [81]:
zeeros = np.zeros((10,10))
zeeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [83]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
tens = np.ones((4,6))*10
tens

array([[10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.]])

In [87]:
empty = np.empty((4,4)) #garbage's values

In [88]:
empty

array([[2.14321575e-312, 2.44029516e-312, 1.29441743e-312,
        2.33419537e-312],
       [9.76118064e-313, 2.33419537e-312, 2.44029516e-312,
        8.48798317e-313],
       [9.33678148e-313, 8.70018275e-313, 8.91238232e-313,
        1.01855798e-312],
       [2.46151512e-312, 2.33419537e-312, 8.45566771e-307,
        1.27945906e-307]])

In [89]:
eye = np.eye(4,5)

In [90]:
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [91]:
onesLike = np.ones_like(t1) # matrix of ones of shape and type of t1

In [92]:
onesLike

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
onesLike > t1

array([[False, False, False],
       [False, False, False]])

In [96]:
t1>5

array([[False,  True,  True],
       [ True,  True, False]])

In [99]:
[t1][t1>5] # will only show those values of t1 that are greater than 5

TypeError: only integer scalar arrays can be converted to a scalar index

# Basic Indexing and Slicing

In [102]:
alist = [1,2,3,4,5,6,7,8,9]

In [104]:
alist[5] #indexing

6

In [105]:
type(alist[5])

int

In [109]:
alist[1:5] #slicing

[2, 3, 4, 5]

In [110]:
type(alist[1:5])

list

In [111]:
twoD = np.arange(100).reshape(10,10)

In [112]:
twoD

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [114]:
twoD[5,4] # selecting 54 by indexing

54

In [115]:
twoD[[5,4],[5,4]]

array([55, 44])