# Numpy 3D Arrays

In [1]:
import numpy as np
d3 = np.arange(50).reshape(2,5,5)
d3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

Indexing 3D Arrays

In [2]:
d3[1,2,1]

36

In [3]:
d3[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

Slicing 3D Arrays

In [4]:
d3[0,2:4,1:3] #result is 2D

array([[11, 12],
       [16, 17]])

In [5]:
d3[0:1,2:4,1:3] #result is 3D

array([[[11, 12],
        [16, 17]]])

In [6]:
d3[1:2,4:5,0:5] #slecting last row of 2nd matrix

array([[[45, 46, 47, 48, 49]]])

In [7]:
d3[1:,4:,0:]

array([[[45, 46, 47, 48, 49]]])

In [8]:
d3[0:,2:4,1:3] #selecting one row frm 1st matrix and one from 2nd matrix

array([[[11, 12],
        [16, 17]],

       [[36, 37],
        [41, 42]]])

In [9]:
d3[1:,:,3:4]

array([[[28],
        [33],
        [38],
        [43],
        [48]]])

# Broadcasting

In [22]:
x= np.array([[1,2,3]])
y = np.array([[1],[2],[3]])

In [23]:
x.shape , y.shape

((1, 3), (3, 1))

In [27]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [28]:
x,y = np.broadcast_arrays(x,y)

In [29]:
x+y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Pandas

# Pandas Data Structure:
    i)Series
    ii)Data Fram

# i)Series

In [106]:
import pandas as pd

In [33]:
s = pd.Series([111,222,333,444,555,666,777]) #shows labels/index and values
s # pandas series object

0    111
1    222
2    333
3    444
4    555
5    666
6    777
dtype: int64

In [35]:
#getting a single series value

s[4]

555

In [39]:
#getting multiple series values

s[[5,0,3,1]]

5    666
0    111
3    444
1    222
dtype: int64

In [40]:
# uppdating a series value

s[3] = 100

In [41]:
s

0    111
1    222
2    333
3    100
4    555
5    666
6    777
dtype: int64

In [42]:
# updating multiple values 

s[[2,4,0]] = [999,123,456]

In [43]:
s

0    456
1    222
2    999
3    100
4    123
5    666
6    777
dtype: int64

In [44]:
# deleting a value in series

del s[4]

In [45]:
s

0    456
1    222
2    999
3    100
5    666
6    777
dtype: int64

In [47]:
# deleting mutiple values in a series

del s[[2,5,6]] # multiple deletions aree not allowed

TypeError: '[2, 5, 6]' is an invalid key

In [48]:
s[1234] = 423531

In [49]:
s

0          456
1          222
2          999
3          100
5          666
6          777
1234    423531
dtype: int64

In [55]:
s[[9,14,45]] = [111,111,111]
# not allowed

ValueError: [ 9 14 45] not contained in the index

In [56]:
s

0          456
1          111
2          111
3          111
5          666
6          777
1234    423531
dtype: int64

In [71]:
s1 = pd.Series([100,200,300,400] , index = ["apples", "oranges", "bananas", "grapes"])

In [72]:
s1

apples     100
oranges    200
bananas    300
grapes     400
dtype: int64

Creating A Series from A Dictionary

In [73]:
aDic = {"Name": "Mehmood" , "Class":"A-1" , "Time":"5-9"}

In [74]:
s2 = pd.Series(aDic)
s2

Name     Mehmood
Class        A-1
Time         5-9
dtype: object

In [75]:
s3 = pd.Series(s1, index=["mango", "oranges" , "bananas" , "grapes"])

In [76]:
s3

mango        NaN
oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [77]:
s3.values

array([ nan, 200., 300., 400.])

In [81]:
 # NaN = Not a Number

In [82]:
s3.index

Index(['mango', 'oranges', 'bananas', 'grapes'], dtype='object')

In [83]:
s3[s3>2]

oranges    200.0
bananas    300.0
grapes     400.0
dtype: float64

In [84]:
"mango" in s3

True

In [85]:
pd.isnull(s3)

mango       True
oranges    False
bananas    False
grapes     False
dtype: bool

In [86]:
s1 + s2

Class      NaN
Name       NaN
Time       NaN
apples     NaN
bananas    NaN
grapes     NaN
oranges    NaN
dtype: object

In [90]:
s4 = pd.Series([100,200,300,400,500] , index = ["tables", "chairs", "books", "pens", "boards"])
s4

tables    100
chairs    200
books     300
pens      400
boards    500
dtype: int64

In [94]:
s3 + s4 #indeces are not same so result is NaN

bananas   NaN
boards    NaN
books     NaN
chairs    NaN
grapes    NaN
mango     NaN
oranges   NaN
pens      NaN
tables    NaN
dtype: float64

In [95]:
s3+s3

mango        NaN
oranges    400.0
bananas    600.0
grapes     800.0
dtype: float64

In [96]:
s4+s4

tables     200
chairs     400
books      600
pens       800
boards    1000
dtype: int64

# ii)DataFrame

In [99]:
df = pd.DataFrame([123,234,345,456]) #shows the number of row and column
df 

0
0  123
1  234
2  345
3  456

In [100]:
df1 = pd.DataFrame(["Red" , "Green", "Blue"] , index=["v1","v2","v3"])
df1

0
v1    Red
v2  Green
v3   Blue

In [101]:
df2 = pd.DataFrame(["Red" , "Green", "Blue"] , index=["v1","v2","v3"], columns=["colours"])
df2

colours
v1     Red
v2   Green
v3    Blue

Creating a Data Fram from a Dictionary

In [102]:
score = {"Ai for E0"  :   [76,78,89,34,45,76,12,34,42,11],
         "Python1"    :   [12,23,34,45,56,67,67,78,89,90],
         "Python2"    :   [13,24,35,46,57,68,79,80,14,47]}

In [146]:
score

{'Ai for E0': [76, 78, 89, 34, 45, 76, 12, 34, 42, 11],
 'Python1': [12, 23, 34, 45, 56, 67, 67, 78, 89, 90],
 'Python2': [13, 24, 35, 46, 57, 68, 79, 80, 14, 47]}

In [147]:
sc = pd.DataFrame(score,index = ["Nasir", "Khalid","Ali","Saad","Asad","Saif","Mehmood","Amjad","Majid","Hammad"])

In [148]:
sc

Ai for E0  Python1  Python2
Nasir           76       12       13
Khalid          78       23       24
Ali             89       34       35
Saad            34       45       46
Asad            45       56       57
Saif            76       67       68
Mehmood         12       67       79
Amjad           34       78       80
Majid           42       89       14
Hammad          11       90       47

In [110]:
sc.head() #by default returns 5 records

Ai for E0  Python1  Python2
Nasir          76       12       13
Khalid         78       23       24
Ali            89       34       35
Saad           34       45       46
Asad           45       56       57

In [113]:
sc.head(3)

Ai for E0  Python1  Python2
Nasir          76       12       13
Khalid         78       23       24
Ali            89       34       35

In [115]:
sc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Nasir to Hammad
Data columns (total 3 columns):
Ai for E0    10 non-null int64
Python1      10 non-null int64
Python2      10 non-null int64
dtypes: int64(3)
memory usage: 320.0+ bytes


In [116]:
sc.describe()

Ai for E0    Python1    Python2
count  10.000000  10.000000  10.000000
mean   49.700000  56.100000  46.300000
std    28.327646  27.081974  24.873234
min    11.000000  12.000000  13.000000
25%    34.000000  36.750000  26.750000
50%    43.500000  61.500000  46.500000
75%    76.000000  75.250000  65.250000
max    89.000000  90.000000  80.000000

In [117]:
sc.Python1 #selecting column Python1

Nasir      12
Khalid     23
Ali        34
Saad       45
Asad       56
Saif       67
Mehmood    67
Amjad      78
Majid      89
Hammad     90
Name: Python1, dtype: int64

In [122]:
sc['Python1']

Nasir      12
Khalid     23
Ali        34
Saad       45
Asad       56
Saif       67
Mehmood    67
Amjad      78
Majid      89
Hammad     90
Name: Python1, dtype: int64

In [126]:
sc[['Ai for E0', 'Python1']]

Ai for E0  Python1
Nasir           76       12
Khalid          78       23
Ali             89       34
Saad            34       45
Asad            45       56
Saif            76       67
Mehmood         12       67
Amjad           34       78
Majid           42       89
Hammad          11       90

In [127]:
sc.loc["Nasir"]

Ai for E0    76
Python1      12
Python2      13
Name: Nasir, dtype: int64

In [129]:
sc.loc[["Nasir","Mehmood"]]

Ai for E0  Python1  Python2
Nasir           76       12       13
Mehmood         12       67       79

In [132]:
sc["extra"]=range(10)
sc

Ai for E0  Python1  Python2  extra
Nasir           76       12       13      0
Khalid          78       23       24      1
Ali             89       34       35      2
Saad            34       45       46      3
Asad            45       56       57      4
Saif            76       67       68      5
Mehmood         12       67       79      6
Amjad           34       78       80      7
Majid           42       89       14      8
Hammad          11       90       47      9

In [133]:
del sc["extra"]

In [149]:
sc

Ai for E0  Python1  Python2
Nasir           76       12       13
Khalid          78       23       24
Ali             89       34       35
Saad            34       45       46
Asad            45       56       57
Saif            76       67       68
Mehmood         12       67       79
Amjad           34       78       80
Majid           42       89       14
Hammad          11       90       47

In [150]:
sc['Total'] = sc['Ai for E0']+ sc['Python1'] + sc['Python2']
sc

Ai for E0  Python1  Python2  Total
Nasir           76       12       13    101
Khalid          78       23       24    125
Ali             89       34       35    158
Saad            34       45       46    125
Asad            45       56       57    158
Saif            76       67       68    211
Mehmood         12       67       79    158
Amjad           34       78       80    192
Majid           42       89       14    145
Hammad          11       90       47    148

In [151]:
sc['Status'] = sc['Total']>150
sc

Ai for E0  Python1  Python2  Total  Status
Nasir           76       12       13    101   False
Khalid          78       23       24    125   False
Ali             89       34       35    158    True
Saad            34       45       46    125   False
Asad            45       56       57    158    True
Saif            76       67       68    211    True
Mehmood         12       67       79    158    True
Amjad           34       78       80    192    True
Majid           42       89       14    145   False
Hammad          11       90       47    148   False

In [158]:
sc['Status'] = np.where(sc['Total']>150,"Pass","Fail") #numpy method
sc

Ai for E0  Python1  Python2  Total Status
Nasir           76       12       13    101   Fail
Khalid          78       23       24    125   Fail
Ali             89       34       35    158   Pass
Saad            34       45       46    125   Fail
Asad            45       56       57    158   Pass
Saif            76       67       68    211   Pass
Mehmood         12       67       79    158   Pass
Amjad           34       78       80    192   Pass
Majid           42       89       14    145   Fail
Hammad          11       90       47    148   Fail

In [157]:
sc["Status"] = ["Pass"if marks>150 else "Fail" for marks in sc["Total"]] #list comprehension method
sc

Ai for E0  Python1  Python2  Total Status
Nasir           76       12       13    101   Fail
Khalid          78       23       24    125   Fail
Ali             89       34       35    158   Pass
Saad            34       45       46    125   Fail
Asad            45       56       57    158   Pass
Saif            76       67       68    211   Pass
Mehmood         12       67       79    158   Pass
Amjad           34       78       80    192   Pass
Majid           42       89       14    145   Fail
Hammad          11       90       47    148   Fail

In [160]:
sc["RevisedStatus"] = np.where((sc['Ai for E0']>=50) & (sc['Python1']>=50) & (sc['Python2']>=50),"Pass","Fail")

In [161]:
sc

Ai for E0  Python1  Python2  Total Status RevisedStatus
Nasir           76       12       13    101   Fail          Fail
Khalid          78       23       24    125   Fail          Fail
Ali             89       34       35    158   Pass          Fail
Saad            34       45       46    125   Fail          Fail
Asad            45       56       57    158   Pass          Fail
Saif            76       67       68    211   Pass          Pass
Mehmood         12       67       79    158   Pass          Fail
Amjad           34       78       80    192   Pass          Fail
Majid           42       89       14    145   Fail          Fail
Hammad          11       90       47    148   Fail          Fail

In [168]:
sc["NewStatus"] = ["Pass" if (ai>=50) and (p1>= 50) and (p2>= 50) else "Fail" for ai,p1,p2 in zip(sc["Ai for E0"] , sc["Python1"], sc["Python2"])]
sc

Ai for E0  Python1  Python2  Total Status RevisedStatus NewStatus
Nasir           76       12       13    101   Fail          Fail      Fail
Khalid          78       23       24    125   Fail          Fail      Fail
Ali             89       34       35    158   Pass          Fail      Fail
Saad            34       45       46    125   Fail          Fail      Fail
Asad            45       56       57    158   Pass          Fail      Fail
Saif            76       67       68    211   Pass          Pass      Pass
Mehmood         12       67       79    158   Pass          Fail      Fail
Amjad           34       78       80    192   Pass          Fail      Fail
Majid           42       89       14    145   Fail          Fail      Fail
Hammad          11       90       47    148   Fail          Fail      Fail