In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [6]:
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a,b  = np.broadcast_arrays(x,y)

In [8]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [9]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
x+y

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])

In [11]:
a+b

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15]])